#!/usr/bin/env bash

# summary
    # this is a wrapper to trick everything into using pnpm instead of npm
if [ "$1" = "install" ] || [ "$1" = "i" ]
then
    shift 1
    pnpm install --ignore-workspace-root-check "$@"
else
    pnpm "$@"
fi